language: php

sudo: false

php:
  - 5.6
  - 7.0

cache:
    - apt

before_install:
 - composer --prefer-source install

script: phpunit --verbose tests/MainTest.php

notifications:
  email: "nurcholid@windowslive.com"

after_success:
- coveralls