# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # aliased to a recent 5.6.x version
  - 5.6

before_install:
  - php /home/travis/.phpenv/versions/5.6/bin/composer.phar self-update

# optionally specify a list of environments, for example to test different RDBMS
env:
  - DB=mysql

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: phpunit --bootstrap index.php Tests/TemplateEngineTest

# configure notifications (email, IRC, campfire etc)
notifications:
  email: "nurcholid@windowslive.com"
