language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6

cache:
    - apt

before_install:
 - composer --prefer-source install

script: phpunit --verbose Tests/Main.php

notifications:
  email: "nurcholid@windowslive.com"